### ISSUE TITLE
Guzzle and tailwind/jit seems to interfere breaking hmr during very low recompile times

### ISSUE THREAD

**Issue by iuscare** [nystudio107/craft#55]
### Describe the bug
Tested this with a fresh new package. When changing something in the twig files, the hmr/webpack seems to lose connection to the browser. The console doesnt output anything anymore and also css/js files are not being loaded anymore, which is able to see on the attached screenshot. This leads to a white blank page. A full page reload works tough and it only seems to affect twig files. Changing css or js files works as expected.

### To reproduce
Steps to reproduce the behaviour:
1. composer create-project nystudio107/craft craft3 --no-install
2. cd craft3
3. make dev (and grab a coffee ☕)
4. visit localhost:8000 and be happy about much confetti 🎉
5. change sth. in index.twig, e.g. in the subcontent block & save
6. see how a white screen of death appears 💀

### Expected behaviour
HMR should work on the twig files the same as on js and css without the need of a full page refresh 

### Screenshots
<img width="2252" alt="Bildschirmfoto 2021-03-30 um 11 57 33" src="https://user-images.githubusercontent.com/33871309/112973487-aca7f900-9151-11eb-8ac4-5c519fc1d5cc.png">
<img width="2453" alt="Bildschirmfoto 2021-03-30 um 12 15 37" src="https://user-images.githubusercontent.com/33871309/112973516-b6316100-9151-11eb-9afa-f985e43cabab.png">

### Versions
```
+-- @babel/core@7.13.14
+-- @babel/plugin-proposal-class-properties@7.13.0
+-- @babel/plugin-proposal-nullish-coalescing-operator@7.13.8
+-- @babel/plugin-proposal-object-rest-spread@7.13.8
+-- @babel/plugin-proposal-optional-chaining@7.13.12
+-- @babel/plugin-syntax-dynamic-import@7.8.3
+-- @babel/plugin-transform-runtime@7.13.10
+-- @babel/preset-env@7.13.12
+-- @babel/preset-typescript@7.13.0
+-- @babel/register@7.13.14
+-- @babel/runtime@7.13.10
+-- @gfx/zopfli@1.0.15
+-- @tailwindcss/jit@0.1.17
+-- @types/node@14.14.37
+-- @types/webpack-env@1.16.0
+-- @typescript-eslint/eslint-plugin@3.10.1
+-- @typescript-eslint/parser@3.10.1
+-- @vue/compiler-sfc@3.0.9
+-- autoprefixer@10.2.5
+-- axios@0.21.1
+-- babel-loader@8.2.2
+-- clean-webpack-plugin@3.0.0
+-- compression-webpack-plugin@6.1.1
+-- copy-webpack-plugin@6.4.1
+-- core-js@3.9.1
+-- create-symlink-webpack-plugin@1.0.1
+-- critical@2.0.6
+-- critical-css-webpack-plugin@2.0.1
+-- css-loader@5.2.0
+-- css-minimizer-webpack-plugin@1.3.0
+-- cssnano@4.1.10
+-- dotenv@6.2.0
+-- eslint@7.23.0
+-- eslint-plugin-vue@7.8.0
+-- favicons@6.2.1
+-- favicons-webpack-plugin@5.0.2
+-- file-loader@6.2.0
+-- get-webpack-config@1.0.0
+-- glob-all@3.2.1
+-- html-webpack-plugin@5.3.1
+-- ignore-loader@0.1.2
+-- imagemin@7.0.1
+-- imagemin-mozjpeg@9.0.0
+-- imagemin-optipng@8.0.0
+-- imagemin-svgo@8.0.0
+-- imagemin-webp@6.0.0
+-- imagemin-webp-webpack-plugin@3.3.3
+-- img-loader@3.0.2
+-- lazysizes@5.3.1
+-- mini-css-extract-plugin@1.4.0
+-- nodemon@2.0.7
+-- postcss@8.2.8
+-- postcss-hexrgba@2.0.1
+-- postcss-import@13.0.0
+-- postcss-loader@4.2.0
+-- postcss-mixins@7.0.3
+-- postcss-nested@5.0.5
+-- regenerator-runtime@0.13.7
+-- save-remote-file-webpack-plugin@1.0.2
+-- style-loader@2.0.0
+-- stylelint@13.12.0
+-- stylelint-config-recommended@3.0.0
+-- symlink-webpack-plugin@0.0.4
+-- tailwindcss@2.0.4
+-- terser-webpack-plugin@5.1.1
+-- ts-loader@8.1.0
+-- tsconfig-paths-webpack-plugin@3.5.1
+-- typescript@4.2.3
+-- typings-for-css-modules-loader@1.7.0
+-- vue@3.0.9
+-- vue-confetti@2.2.1
+-- vue-loader@16.2.0
+-- webpack@5.28.0
+-- webpack-bundle-analyzer@4.4.0
+-- webpack-cli@4.6.0
+-- webpack-dev-server@4.0.0-beta.1
+-- webpack-manifest-plugin@3.1.0
+-- webpack-merge@5.7.3
`-- workbox-webpack-plugin@6.1.2
```

**Comment by khalwat** [comment]
I just tested this with https://github.com/nystudio107/devmode which uses the same setup, and the good news is the HMR of Twig continues to work as expected. I'll have a look at a fresh setup of the scaffolding to see if something was missed.

**Comment by iuscare** [comment]
This seems tailwindcss/jit related. When I disable tailwindcss/jit on the craft package the issue is no longer replicable. But I dont know yet why this happens, you are using tailwindcss/jit on devmode, too. Are the versions different?

**Comment by khalwat** [comment]
Possibly. I think I've set the semver to `latest` so perhaps you're getting a broken build? Maybe set it to an officially tagged release version?

**Comment by iuscare** [comment]
Already tried it. Very strange. All directions lead to the same behavior. I explicitly set the versions of craftcms, twigpack and jit to the same versions as in the lock files of your devmode package-lock.json & composer.lock and still no success. As long as jit is enabled, the issue persists on the craft3 package, whereas devmode works on my end totally fine, too.

**Comment by khalwat** [comment]
okay I will have a look when I'm able

**Comment by iuscare** [comment]
So it seems to downgrade twigpack to a version before Guzzle was introduced in version `1.2.11` temporarily solves the issue at least for me. Can't really tell what's going on, because I know that devmode and this boilerplate rely on the same twigpack version, but there appears a stack trace in the craft debug bar when modifying twig files, which pointed me into that direction. The stack trace appears with version `1.2.11` in both, the devmode and this boilerplate package, although only this boilerplate seems to lose connection to the dev-server/manifest.json or HMR in general. Downgrading twigpack below `1.2.11` let the stack trace disappear and webpack working as expected with tailwind jit in place on my machine.

<img width="1996" alt="Bildschirmfoto 2021-04-02 um 16 10 49" src="https://user-images.githubusercontent.com/33871309/113424851-213c9b00-93d1-11eb-85fa-df7dd71af1e8.png">

**Comment by khalwat** [comment]
@iuscare why is it trying to connect to port `8000` in this case? Shouldn't it be `8080`?

**Comment by khalwat** [comment]
@iuscare I pushed a change that may fix it; I think it may be as simple as we're not catching all of the exceptions that Guzzle might throw: https://github.com/nystudio107/craft-twigpack/commit/0f2d400ef5b512461b9a64411d81859a74a5dda6

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-twigpack": "dev-develop as 1.2.12”,
```
Then do a `composer clear-cache && composer update`

**Comment by qbasic16** [comment]
I'm not familiar with how `nystudio107/craft` is set up, but this path looks quite odd:

![image](https://user-images.githubusercontent.com/13191383/113430652-cdcf4a80-93da-11eb-8552-e8780e40f4bf.png)

Shouldn't it be just `http://localhost:8000/dist/manifest-legacy.json`?

**Comment by iuscare** [comment]
As far as I understand the setup, in devmode we are only building a modern config, therefore the right path to the manifest would be localhost:8080/manifest.json. I can access the manifest file under that path with the browser, but even after clearing caches & pulling in the fast fix provided by @khalwat the issue still persists with the same debug message. I am using exactly the same twigpack config file, which comes with this craft3 package. No customizations to the package were made in any way. Plus the error only appears when `tailwind/jit` is enabled. With default tailwind in aot mode no errors from guzzle appears and everything works out of the box. If I can assist in debugging any further please let me know.

@khalwat you may be able to see this error in the craft debug bar of devmode.fm too, when enabling the bar for the frontend and trying to make a change in a twig file.

**Comment by qbasic16** [comment]
@iuscare I think there is still a bug when you don't use 'combined':

If you only build for "modern" then you should rename the part `'legacy' => 'manifest-legacy.json'` to `'legacy' => 'manifest.json'`.
![image](https://user-images.githubusercontent.com/13191383/113433586-c3fc1600-93df-11eb-9c13-89f32f58da5c.png)

**Comment by iuscare** [comment]
I may put it in a misleading way. In production mode the package builds both, a legacy and a modern manifest, which are defined in the manifest array. But for local development (devmode) the legacy manifest should be dropped performance wise, because we do not need to support multiple devices/browsers here. `devServerBuildType` only indicates which manifest should be used during local development, which could also be set to combined if we'd really want to have both. So to me the config seems to be correct or am I missing something?

**Comment by khalwat** [comment]
I want to focus on why Twigpack 1.2.10 works, and after the PR, 1.2.11 does not, with the same config.

**Comment by khalwat** [comment]
Did you try 1.2.12 @iuscare ?

**Comment by iuscare** [comment]
@khalwat yes, sadly same behavior as before. You can also drop a msg on discord. User is Pascal#3565 in case I can help out in any way

**Comment by iuscare** [comment]
Could it be, that some process has not finished yet? Activated xdebug, which raises the response time of craft above 250-300ms on my end. In this case the error does not happen, when using tailwind jit and twigpack 1.2.11/12

**Comment by khalwat** [comment]
Yep, it's definitely a race condition of some sort.  I'm not even sure this is a bug in Twigpack anymore, but rather that the PR made the request fetching faster, perhaps fast enough that it happens before a process on the server is done rebuilding.

Here's the log of requests the containers are handling after I change something in a template and hit save:

```
php_1         | 192.168.0.5 -  02/Apr/2021:22:35:55 +0000 "GET /index.php" 200
php_1         | 192.168.0.5 -  02/Apr/2021:22:35:55 +0000 "POST /index.php" 200
webpack_1     | <i> [webpack-dev-middleware] wait until bundle finished: /manifest.json
webpack_1     | <i> [webpack-dev-middleware] wait until bundle finished: /manifest.json
webpack_1     | <i> [webpack-dev-middleware] wait until bundle finished: /manifest.json
webpack_1     | <i> [webpack-dev-middleware] wait until bundle finished: /manifest.json
webpack_1     | <i> [webpack-dev-middleware] wait until bundle finished: /manifest.json
webpack_1     | <i> [webpack-dev-middleware] wait until bundle finished: /manifest.json
php_1         | 192.168.0.5 -  02/Apr/2021:22:35:55 +0000 "GET /index.php" 200
php_1         | 192.168.0.5 -  02/Apr/2021:22:35:55 +0000 "POST /index.php" 200
redis_1       | 7:M 02 Apr 2021 22:35:55.589 * 100 changes in 300 seconds. Saving...
redis_1       | 7:M 02 Apr 2021 22:35:55.589 * Background saving started by pid 16
redis_1       | 16:C 02 Apr 2021 22:35:55.593 * DB saved on disk
redis_1       | 16:C 02 Apr 2021 22:35:55.594 * RDB: 0 MB of memory used by copy-on-write
webpack_1     | assets by status 2.3 MiB [cached] 6 assets
webpack_1     | asset manifest.json 437 bytes [emitted]
webpack_1     | Entrypoint app 1.66 MiB = js/runtime.js 46.6 KiB js/app.js 1.61 MiB
webpack_1     | Entrypoint lazysizes-wrapper 584 KiB = js/runtime.js 46.6 KiB js/lazysizes-wrapper.js 537 KiB
webpack_1     | cached modules 598 KiB (javascript) 30.9 KiB (runtime) [cached] 77 modules
webpack_1     | ./node_modules/css-loader/dist/cjs.js??clonedRuleSet-4.use[1]!./node_modules/postcss-loader/dist/cjs.js??clonedRuleSet-4.use[2]!../src/css/app.pcss 13 KiB [built]
webpack_1     | example-project (webpack 5.30.0) compiled successfully in 200 ms
redis_1       | 7:M 02 Apr 2021 22:35:55.690 * Background saving terminated with success
php_1         | 192.168.0.5 -  02/Apr/2021:22:36:00 +0000 "GET /index.php" 200
php_1         | 192.168.0.5 -  02/Apr/2021:22:36:01 +0000 "GET /index.php" 200
```

**Comment by khalwat** [comment]
yeah so if I put a `sleep(1);` in before issuing the request with Guzzle, it works fine.

Also if I turn `devMode` off (which allows the cache to work), then it works fine too.

So there's something about the simultaneous Guzzle requests being sent out so quickly that's causing it.

**Comment by khalwat** [comment]
Well, I don't love it, but it does fix it: <https://github.com/nystudio107/craft-twigpack/commit/b4f2c34b8c938d6b899261c5b562ca5c5a71119f>
